# generate from notebook: !conda env export > environment.yml
name: python

channels:
    - conda-forge
    - defaults

dependencies:
  - python
  - pip
  - pip:
    - matplotlib
    - numpy
    - pandas
    - scipy
    - networkx
    - sphinx
    - cvxpy
    - cvxopt
    - openpyxl
    - nbsphinx
